- hosts: dockerhost
  gather_facts: no
  tasks:
    - name: conf yum for the docker
      yum_repository:
             name: dockerrepo
             baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
             description: yum for the docker
             gpgcheck: no

    - name: install docker software
      command: "yum install docker-ce -y --nobest"

    - name: start docker service
      service:
            name: "docker"
            state: started
            enabled: yes

    - name: install software python36
      package:
            name: "python36"
            state: present

    - name: install docker python library
      pip:
           name: docker-py

    - name: pull httpd for docker
      docker_image:
            name: "httpd"
            source: pull

    - name: copy the file
      copy:
          src: "docker.html"
          dest: "/var/www/html/"

    - name: run httpd
      docker_container:
            name: myweb
            image: httpd
            state: started      
            exposed_ports: 
               - "80"
            ports:
               - "8081:80"
            volumes:
               - /var/www/html:/usr/local/apache2/htdocs/
            tty: true
            detach: true
